server.port=9090
server.address=0.0.0.0

# spring.datasource.url=jdbc:oracle:thin:@//127.0.0.1:1521/siqtech
spring.datasource.url=jdbc:oracle:thin:@194.165.140.205:1521:siqtech
spring.datasource.username=ikhealth
spring.datasource.password=ikhealth
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
