package com.api.demo.dao;

public interface HISDmlStatement {

    /* ===================== PATIENT QUERIES ===================== */
    
    String GET_NEXT_PATIENT_NO = 
        "SELECT NVL(MAX(TO_NUMBER(PATIENT_NO)),0)+1 FROM IKHEALTH.SYS_PATIENTS";
    
    String CHECK_NATIONAL_ID = 
        "SELECT COUNT(*) FROM IKHEALTH.SYS_PATIENTS WHERE NATIONAL_ID_NO = ?";
    
    String CHECK_PATIENT_NO = 
        "SELECT COUNT(*) FROM IKHEALTH.SYS_PATIENTS WHERE PATIENT_NO = ?";
    
    /* ===================== INSERT QUERIES ===================== */
    
    String INSERT_SYS_PATIENTS = 
        "INSERT INTO IKHEALTH.SYS_PATIENTS (" +
        "ID, SITE_ID, PATIENT_NO, NATIONAL_VALUE, SEX, DATE_OF_BIRTH, BIRTH_PLACE, " +
        "FIRST_NAME_A, FATHER_NAME_A, GRANDFATHER_NAME_A, LAST_NAME_A, " +
        "FIRST_NAME_E, FATHER_NAME_E, GRANDFATHER_NAME_E, LAST_NAME_E, " +
        "NATIONAL_ID_NO, FULL_NAME_ARB, FULL_NAME_ENG, FLTR_FULL_NAME_ARB, FLTR_FULL_NAME_ENG, " +
        "CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, LAST_UPDATED_TRANSACTION, " +
        "ALIAS_FLAG, ACC_CODE, ACCOUNT_ID, FILE_STATUS, PATIENT_TITLE_VALUE, BLD_GROUP, RHESUS_FACTOR, " +
        "MOTHER_NATIONAL_ID, FATHER_NATIONAL_ID, PATIENT_PHOTO, RESIDENCY_CARD_IMG, INACTIVE_DATE" +
        ") VALUES (SYS_PATIENTS_SEQ.NEXTVAL, ?, ?, ?, ?, ?, ?, " +
        "?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, " +
        "?, SYSDATE, ?, SYSDATE, ?, ?, NULL, NULL, NULL, NULL, NULL, NULL, " +
        "NULL, NULL, NULL, NULL, SYSDATE)";
    
    String INSERT_SYS_PATIENT_DETAILS = 
        "INSERT INTO IKHEALTH.SYS_PATIENT_DETAILS (" +
        "PATIENT_ID, MARITAL_STATUS_VALUE, PATIENT_TYPE, PATIENT_CLASS_VALUE, " +
        "EMPLOYEE_RANK_VALUE, OCCUPATION_VALUE, EDUCATION_LEVEL_VALUE, PATIENT_LANG_VALUE, " +
        "COMPLETE_FLAG, MOBILE_NO, HOME_PHONE, WORK_PHONE, E_MAIL, ADRESS, ADDRESS2, " +
        "POST_CODE, P_O_BOX, PATIENT_NOTES, CREATED_BY, CREATION_DATE, " +
        "LAST_UPDATED_BY, LAST_UPDATED_DATE, LAST_UPDATED_TRANSACTION" +
        ") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, " +
        "?, SYSDATE, ?, SYSDATE, ?)";
    
    /* ===================== SELECT QUERIES ===================== */
    
    String SELECT_PATIENT_BY_ID = 
        "SELECT * FROM IKHEALTH.SYS_PATIENTS WHERE ID = ?";
    
    String SELECT_PATIENT_DETAILS_BY_ID = 
        "SELECT * FROM IKHEALTH.SYS_PATIENT_DETAILS WHERE PATIENT_ID = ?";
    
    String SELECT_PATIENT_BY_NUMBER = 
        "SELECT * FROM IKHEALTH.SYS_PATIENTS WHERE PATIENT_NO = ?";
    
    /* ===================== UPDATE QUERIES ===================== */
    
    String UPDATE_SYS_PATIENTS = 
        "UPDATE IKHEALTH.SYS_PATIENTS SET " +
        "FIRST_NAME_A = ?, FATHER_NAME_A = ?, GRANDFATHER_NAME_A = ?, LAST_NAME_A = ?, " +
        "FIRST_NAME_E = ?, FATHER_NAME_E = ?, GRANDFATHER_NAME_E = ?, LAST_NAME_E = ?, " +
        "SEX = ?, DATE_OF_BIRTH = ?, BIRTH_PLACE = ?, NATIONAL_ID_NO = ?, NATIONAL_VALUE = ?, " +
        "LAST_UPDATED_BY = ?, LAST_UPDATED_DATE = SYSDATE, LAST_UPDATED_TRANSACTION = 'U' " +
        "WHERE ID = ?";
    
    String UPDATE_SYS_PATIENT_DETAILS = 
        "UPDATE IKHEALTH.SYS_PATIENT_DETAILS SET " +
        "MARITAL_STATUS_VALUE = ?, MOBILE_NO = ?, E_MAIL = ?, ADRESS = ?, " +
        "LAST_UPDATED_BY = ?, LAST_UPDATED_DATE = SYSDATE, LAST_UPDATED_TRANSACTION = 'U' " +
        "WHERE PATIENT_ID = ?";
}