DbUsername=ikhealth
DbPassword=ikhealth
# DBURL=jdbc:oracle:thin:@194.165.140.205:1521:siqtech
DBURL=jdbc:oracle:thin:@192.168.0.161:1521:siqhealth

#######################3
######wsUsername = Abdulhadi.123
######wsPassword = Abdulhadi.123#

wsUsername = Ismail.305
wsPassword = Ismail.305$

license = JOR-P-000305

AuthPostRequest = https://tpo-stg.ehc.jo/api/Authorization/PostRequest
AuthGetNew = https://tpo-stg.ehc.jo/api/Authorization/GetNew
AuthView = https://tpo-stg.ehc.jo/api/Authorization/View
AuthDownload = https://tpo-stg.ehc.jo/api/Authorization/SetDownloaded
EditERXOrderRequest = https://tpo-stg.ehc.jo/api/ERX/EditRequest
EditLABOrderRequest = https://tpo-stg.ehc.jo/api/Lab/EditRequest
EditRADOrderRequest = https://tpo-stg.ehc.jo/api/Rad/EditRequest
ViewLABOrder=https://tpo-stg.ehc.jo/api/Lab/ViewLaboratoryOrder
ViewERXOrder=https://tpo-stg.ehc.jo/api/ERX/ViewPharmacyPrescription
ViewRADOrder=https://tpo-stg.ehc.jo/api/Rad/ViewRadiologyOrder
dispenseLab=https://tpo-stg.ehc.jo/api/Dispense/LabDispense
dispenseRad=https://tpo-stg.ehc.jo/api/Dispense/RadDispense
dispensePhr=https://tpo-stg.ehc.jo/api/Dispense/ErxDispense
ClaimGetNew = https://TPO.ehc.jo/api/Claim/GetNew
ClaimViewCall = https://TPO.ehc.jo/api/Claim/View
ClaimDownload = https://TPO.ehc.jo/api/Claim/SetDownloaded
clmPostSubmission = https://TPO.ehc.jo/api/Claim/PostSubmission

# ISTD 

AuthISTD = https://backend.jofotara.gov.jo/core/invoices/
